name: semana_backend
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.3 <3.0.0'

dependencies:
  shelf: ^1.3.2
  shelf_modular: ^2.0.1
  postgres: ^2.4.5

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
